"""
ProcessLens - process analysis.

Reads the generated jobs data and answers the questions a consultant would ask
when reviewing a business process:

  1. Conversion funnel - where do we lose work?
  2. Stage cycle times - which stage is the bottleneck?
  3. Rework rate - how much do quality failures cost us in time?
  4. Improvement scenario - what if we cut the worst stage by 40%?

Outputs:
  outputs/funnel.png
  outputs/cycle_times.png
  outputs/summary.md
"""

from __future__ import annotations
from pathlib import Path
import sqlite3
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

BASE = Path(__file__).parent
OUT = BASE / "outputs"
DB = BASE / "data" / "processlens.db"

STAGE_PAIRS = [
    ("lead_dt", "quoted_dt", "Lead to Quote"),
    ("quoted_dt", "scheduled_dt", "Quote to Schedule"),
    ("scheduled_dt", "completed_dt", "Schedule to Complete"),
    ("completed_dt", "invoiced_dt", "Complete to Invoice"),
    ("invoiced_dt", "paid_dt", "Invoice to Payment"),
]


def load() -> pd.DataFrame:
    con = sqlite3.connect(DB)
    df = pd.read_sql("SELECT * FROM jobs", con,
                     parse_dates=["lead_dt", "quoted_dt", "scheduled_dt",
                                  "completed_dt", "invoiced_dt", "paid_dt"])
    con.close()
    return df


def funnel(df: pd.DataFrame) -> pd.Series:
    stages = {
        "Leads": df["lead_dt"].notna().sum(),
        "Quoted": df["quoted_dt"].notna().sum(),
        "Scheduled": df["scheduled_dt"].notna().sum(),
        "Completed": df["completed_dt"].notna().sum(),
        "Invoiced": df["invoiced_dt"].notna().sum(),
        "Paid": df["paid_dt"].notna().sum(),
    }
    return pd.Series(stages)


def cycle_times(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for a, b, label in STAGE_PAIRS:
        delta = (df[b] - df[a]).dt.total_seconds() / 86400.0
        delta = delta.dropna()
        rows.append({
            "stage": label,
            "median_days": round(delta.median(), 2),
            "mean_days": round(delta.mean(), 2),
            "p90_days": round(delta.quantile(0.90), 2),
        })
    return pd.DataFrame(rows)


def plot_funnel(f: pd.Series) -> None:
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.barh(f.index[::-1], f.values[::-1], color="#1f4e79")
    ax.set_title("Order-to-cash funnel")
    ax.set_xlabel("Number of jobs")
    for i, v in enumerate(f.values[::-1]):
        ax.text(v + 5, i, str(int(v)), va="center", fontsize=9)
    fig.tight_layout()
    fig.savefig(OUT / "funnel.png", dpi=130)
    plt.close(fig)


def plot_cycle(ct: pd.DataFrame) -> None:
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(ct["stage"], ct["median_days"], color="#c55a11")
    ax.set_title("Median cycle time by stage")
    ax.set_ylabel("Days")
    ax.set_xticks(range(len(ct)))
    ax.set_xticklabels(ct["stage"], rotation=25, ha="right", fontsize=8)
    fig.tight_layout()
    fig.savefig(OUT / "cycle_times.png", dpi=130)
    plt.close(fig)


def main() -> None:
    OUT.mkdir(exist_ok=True)
    df = load()
    f = funnel(df)
    ct = cycle_times(df)

    # Headline metrics
    lead_to_quote_loss = 1 - f["Scheduled"] / f["Quoted"]
    rework_rate = df.loc[df["status"] != "lost", "rework_flag"].mean()
    bottleneck = ct.sort_values("median_days", ascending=False).iloc[0]
    total_median = ct["median_days"].sum()
    # Scenario: cut the worst stage's median by 40%
    saving = bottleneck["median_days"] * 0.40
    new_total = total_median - saving

    plot_funnel(f)
    plot_cycle(ct)

    md = []
    md.append("# ProcessLens - findings (synthetic data)\n")
    md.append("> Fictional company: **Brightway Facilities Services**. "
              "All data is synthetic and generated by `generate_data.py`.\n")
    md.append("## Headline findings\n")
    md.append(f"- **Quote-to-schedule drop-off:** {lead_to_quote_loss:.0%} of "
              "quoted jobs never convert to a booking.")
    md.append(f"- **Bottleneck stage:** *{bottleneck['stage']}* at a median of "
              f"**{bottleneck['median_days']} days** "
              f"(90th percentile {bottleneck['p90_days']} days).")
    md.append(f"- **Rework rate:** {rework_rate:.1%} of completed jobs are "
              "redone due to quality issues, adding delay and cost.")
    md.append(f"- **End-to-end median cycle:** {total_median:.1f} days.\n")
    md.append("## Improvement scenario\n")
    md.append(f"Cutting the *{bottleneck['stage']}* stage by 40% (e.g. via "
              "automated invoice generation / templated quoting) would save "
              f"~**{saving:.1f} days** per job, reducing the end-to-end cycle "
              f"to ~**{new_total:.1f} days** ({saving/total_median:.0%} faster).\n")
    md.append("## Cycle time table\n")
    md.append(ct.to_markdown(index=False))
    (OUT / "summary.md").write_text("\n".join(md))

    print("Cycle times:\n", ct.to_string(index=False))
    print(f"\nBottleneck: {bottleneck['stage']} ({bottleneck['median_days']} days)")
    print(f"Rework rate: {rework_rate:.1%}")
    print("Wrote outputs/funnel.png, outputs/cycle_times.png, outputs/summary.md")


if __name__ == "__main__":
    main()
